disabled_rules:
  - trailing_whitespace
  - line_length
  - force_cast
  - function_body_length
  - type_body_length

opt_in_rules:
  - empty_count
  - empty_string

excluded:
  - Package.swift
  - .build
  - Trash

min_class_length: 0
min_function_length: 0
