name: KryptoClaw
options:
  bundleIdPrefix: com.kryptoclaw
  deploymentTarget:
    iOS: "17.0"
packages:
  web3.swift:
    url: https://github.com/argentlabs/web3.swift.git
    exactVersion: "1.1.0"
  BigInt:
    url: https://github.com/attaswift/BigInt.git
    from: "5.3.0"
  CryptoSwift:
    url: https://github.com/krzyzanowskim/CryptoSwift.git
    from: "1.8.0"
  secp256k1:
    url: https://github.com/Boilertalk/secp256k1.swift.git
    from: "0.1.7"
  WalletCore:
    url: https://github.com/trustwallet/wallet-core
    exactVersion: "4.3.23"
targets:
  KryptoClaw:
    type: application
    platform: iOS
    sources:
      - path: Sources/KryptoClaw
        excludes:
          - "**/.DS_Store"
    resources:
      - path: Sources/KryptoClaw/Resources
      - path: Sources/KryptoClaw/Info.plist
      - path: Sources/KryptoClaw/PrivacyInfo.xcprivacy
    dependencies:
      - package: web3.swift
        product: web3.swift
      - package: BigInt
      - package: CryptoSwift
      - package: secp256k1
        product: secp256k1
      - package: WalletCore
        product: WalletCore
      - package: WalletCore
        product: WalletCoreSwiftProtobuf
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kryptoclaw.app
        INFOPLIST_FILE: Sources/KryptoClaw/Info.plist
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Sources/KryptoClaw/Info.plist
      properties:
        CFBundleName: KryptoClaw
        CFBundleDisplayName: KryptoClaw
        CFBundleIdentifier: com.kryptoclaw.app
        CFBundleVersion: "1.0"
        CFBundleShortVersionString: "1.0"
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
