name: KryptoClaw
options:
  bundleIdPrefix: com.kryptoclaw
  deploymentTarget:
    iOS: "17.0"
packages:
  KryptoClaw:
    path: .
    products:
      - KryptoClaw
targets:
  KryptoClawApp:
    type: application
    platform: iOS
    sources:
      - path: Sources/KryptoClaw
        excludes:
          - "**/*Tests.swift"
    dependencies: []
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kryptoclaw.app
        INFOPLIST_FILE: Sources/KryptoClaw/Info.plist
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    info:
      path: Sources/KryptoClaw/Info.plist
      properties:
        CFBundleName: KryptoClaw
        CFBundleDisplayName: KryptoClaw
        CFBundleIdentifier: com.kryptoclaw.app
        CFBundleVersion: "1.0"
        CFBundleShortVersionString: "1.0"
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
